#!/usr/bin/env bash
# =============================================================================
# session-start-ensure-git-hooks.sh — SessionStart (NEU in v2.0)
#
# Macht die git-Hooks "plug and active". Schließt zwei Lücken aus v1.x:
#   1. install-git-hooks.sh musste manuell pro App ausgeführt werden — wer den
#      Schritt übersprang, hatte Ticket-ID-Zwang/gitleaks/Pre-Push-Tests nie.
#   2. Die Wrapper pinnten den absoluten Cache-Pfad der damals installierten
#      Version. Nach jedem Plugin-Update liefen die git-Hooks auf dem alten
#      Stand weiter.
#
# Verhalten (bewusst konservativ, schweigend wenn nichts zu tun ist):
#   - Kein git-Repo -> exit
#   - Plugin-Source-Checkout (dieses Repo selbst) -> exit; dort zeigen die
#     Hooks absichtlich auf den Arbeitsstand, nicht auf den Cache
#   - Installiert/erneuert NUR wenn eines von beidem gilt:
#       a) unsere Hooks sind schon da (Marker "auto-generated by work-convention")
#          aber zeigen auf einen anderen PLUGIN_ROOT als den aktuellen -> refresh
#       b) die App ist als Empire-App markiert (.env mit APP_PROJECT_PREFIX)
#          und Hooks fehlen -> frische Installation
#     Fremde Repos ohne Marker und ohne Empire-.env werden NIE angefasst.
#   - Genau eine Ausgabezeile, wenn etwas getan wurde. Sonst Stille —
#     Session-Start-Output ist Kontext, und Kontext kostet in jeder Session.
# =============================================================================
set -uo pipefail

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-}"
[ -z "$PLUGIN_ROOT" ] && exit 0
[ -x "$PLUGIN_ROOT/scripts/install-git-hooks.sh" ] || exit 0

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
git -C "$PROJECT_DIR" rev-parse --git-dir >/dev/null 2>&1 || exit 0

# Plugin-Source-Checkout? Nicht anfassen (Entwicklung läuft gegen den Repo-Stand).
[ -f "$PROJECT_DIR/plugins/work-convention/.claude-plugin/plugin.json" ] && exit 0

GIT_DIR="$(git -C "$PROJECT_DIR" rev-parse --git-dir 2>/dev/null)"
[[ "$GIT_DIR" = /* ]] || GIT_DIR="$PROJECT_DIR/$GIT_DIR"
HOOKS_DIR="$GIT_DIR/hooks"
MARKER="auto-generated by work-convention"

ours_installed=0
stale=0
for h in commit-msg pre-commit pre-push; do
  if [ -f "$HOOKS_DIR/$h" ] && grep -q "$MARKER" "$HOOKS_DIR/$h" 2>/dev/null; then
    ours_installed=1
    grep -q "$PLUGIN_ROOT" "$HOOKS_DIR/$h" 2>/dev/null || stale=1
  else
    # Mindestens einer fehlt oder ist fremd -> bei Empire-App neu installieren
    stale=1
  fi
done

if [ "$ours_installed" -eq 0 ]; then
  # Noch nie installiert: nur in markierten Empire-Apps aktiv werden.
  grep -qE '^APP_PROJECT_PREFIX=.+' "$PROJECT_DIR/.env" 2>/dev/null || exit 0
fi

[ "$ours_installed" -eq 1 ] && [ "$stale" -eq 0 ] && exit 0

# Fremde (nicht-Marker) Hooks nie überschreiben — einzeln prüfen:
for h in commit-msg pre-commit pre-push; do
  if [ -f "$HOOKS_DIR/$h" ] && ! grep -q "$MARKER" "$HOOKS_DIR/$h" 2>/dev/null; then
    echo "⚠️  work-convention: $HOOKS_DIR/$h existiert und ist nicht von uns — git-Hooks nicht angefasst." >&2
    exit 0
  fi
done

if (cd "$PROJECT_DIR" && bash "$PLUGIN_ROOT/scripts/install-git-hooks.sh" >/dev/null 2>&1); then
  echo "🔗 git-Hooks auf aktuelle Plugin-Version gezogen ($HOOKS_DIR)."
fi
exit 0
