#!/usr/bin/env bash
# =============================================================================
# healthcheck.sh — prüft ob das Plugin in einer App korrekt verdrahtet ist.
# v2.0: geschrumpft auf das, was es noch gibt. ClickUp/Slack/Status-Checks
#       sind mit den zugehörigen Features entfallen.
# Verwendung:  cd /path/to/app && bash <plugin>/scripts/healthcheck.sh
# =============================================================================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
APP_DIR="$(pwd)"

OK=0; WARN=0; ERR=0
ok()   { echo "  ✅ $1"; OK=$((OK+1)); }
warn() { echo "  ⚠️  $1"; WARN=$((WARN+1)); }
err()  { echo "  ❌ $1"; ERR=$((ERR+1)); }

echo "═══ Plugin-Files ($PLUGIN_ROOT) ═══"
HOOK_COUNT=$(ls "$PLUGIN_ROOT/hooks/"*.sh 2>/dev/null | wc -l | tr -d ' ')
[ "$HOOK_COUNT" -eq 13 ] && ok "$HOOK_COUNT Hook-Scripts" || warn "erwartet 13 Hook-Scripts, gefunden: $HOOK_COUNT"
[ -f "$PLUGIN_ROOT/hooks/hooks.json" ] && ok "hooks.json" || err "hooks.json fehlt"
AGENT_COUNT=$(ls "$PLUGIN_ROOT/agents/"*.md 2>/dev/null | wc -l | tr -d ' ')
[ "$AGENT_COUNT" -eq 7 ] && ok "7 Agents" || warn "erwartet 7 Agents, gefunden: $AGENT_COUNT"
NO_PIN=$(grep -L "^model:" "$PLUGIN_ROOT/agents/"*.md 2>/dev/null | wc -l | tr -d ' ')
[ "$NO_PIN" -eq 0 ] && ok "alle Agents haben Model-Pins" || err "$NO_PIN Agent(s) ohne model: — erben Hauptmodell"

echo ""
echo "═══ Git-Hooks (App-lokal) ═══"
if git -C "$APP_DIR" rev-parse --git-dir >/dev/null 2>&1; then
  GIT_DIR="$(git -C "$APP_DIR" rev-parse --git-common-dir)"
  [[ "$GIT_DIR" = /* ]] || GIT_DIR="$APP_DIR/$GIT_DIR"
  for h in commit-msg pre-commit pre-push; do
    if [ -x "$GIT_DIR/hooks/$h" ] && grep -q "auto-generated by work-convention" "$GIT_DIR/hooks/$h" 2>/dev/null; then
      if grep -q "$PLUGIN_ROOT" "$GIT_DIR/hooks/$h" 2>/dev/null; then
        ok "$h installiert (aktuelle Version)"
      else
        warn "$h zeigt auf alte Plugin-Version — nächster Session-Start zieht nach"
      fi
    else
      warn "$h nicht installiert — nächster Session-Start installiert (braucht APP_PROJECT_PREFIX in .env)"
    fi
  done
else
  warn "kein git-Repo — git-Hook-Checks übersprungen"
fi

echo ""
echo "═══ App-Config (.env) ═══"
if [ -f "$APP_DIR/.env" ]; then
  grep -qE '^APP_PROJECT_PREFIX=.+' "$APP_DIR/.env" && ok "APP_PROJECT_PREFIX gesetzt (Empire-App-Marker)" \
    || err "APP_PROJECT_PREFIX fehlt — ensure-git-hooks bleibt inaktiv, Ticket-Format undefiniert"
  grep -qE '^CURRENT_OPERATOR="?(patrick|justin)"?' "$APP_DIR/.env" && ok "CURRENT_OPERATOR valide" \
    || warn "CURRENT_OPERATOR sollte 'patrick' oder 'justin' sein"
else
  warn ".env fehlt — cp .env.example .env (APP_PROJECT_PREFIX nötig für git-Hooks)"
fi

echo ""
echo "═══ Tacho & Selbstversorgung (v2.1) ═══"
if jq -e '.statusLine' "$HOME/.claude/settings.json" >/dev/null 2>&1; then
  ok "Statusline konfiguriert (~/.claude/settings.json)"
else
  warn "Statusline nicht konfiguriert — Opt-in-Snippet: docs/STATUSLINE.md im Plugin-Repo"
fi
if [ -f "$HOME/.claude/.work-convention-last-update-check" ]; then
  ok "Self-Update-Hook ist gelaufen (Marker vorhanden)"
else
  warn "Self-Update noch nie gelaufen — kommt beim nächsten Session-Start (≥v2.1)"
fi

echo ""
echo "═══ Tools ═══"
for t in git jq; do command -v "$t" >/dev/null 2>&1 && ok "$t" || err "$t fehlt (Hooks brauchen es)"; done
command -v gitleaks >/dev/null 2>&1 && ok "gitleaks" || warn "gitleaks fehlt — pre-commit Secret-Scan übersprungen (brew install gitleaks)"
command -v gh >/dev/null 2>&1 && ok "gh-cli" || warn "gh-cli fehlt (optional)"

echo ""
echo "═══ Summary ═══"
echo "  ✅ $OK / ⚠️  $WARN / ❌ $ERR"
[ "$ERR" -gt 0 ] && { echo "  🚨 $ERR kritische Fehler."; exit 1; }
exit 0
