#!/usr/bin/env bash
# =============================================================================
# install-git-hooks.sh — Installer für git-Hooks (commit-msg, pre-commit, pre-push)
#
# Wird einmalig pro App ausgeführt. Setzt git-Hooks die Plugin-Scripts ausführen.
# Verwendung:
#   cd /path/to/your/app
#   bash ~/.claude/plugins/cache/kornmueller-empire/work-convention/<version>/scripts/install-git-hooks.sh
# =============================================================================
set -uo pipefail

# Plugin-Root: wo dieses Script liegt
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# App-Repo-Root finden
APP_DIR="$(pwd)"
if ! git -C "$APP_DIR" rev-parse --git-dir &>/dev/null; then
  echo "❌ Nicht in einem Git-Repo. Wechsel in dein App-Verzeichnis." >&2
  exit 1
fi
# --git-common-dir: in Linked Worktrees liest git Hooks nur aus dem Common Dir.
GIT_DIR="$(git -C "$APP_DIR" rev-parse --git-common-dir)"
[[ "$GIT_DIR" = /* ]] || GIT_DIR="$APP_DIR/$GIT_DIR"

echo "📍 Plugin-Root: $PLUGIN_ROOT"
echo "📍 Git-Dir:     $GIT_DIR"
echo ""

HOOKS_DIR="$GIT_DIR/hooks"
mkdir -p "$HOOKS_DIR"

# commit-msg-Hook (für Ticket-ID-Required)
cat > "$HOOKS_DIR/commit-msg" <<HOOK
#!/usr/bin/env bash
# auto-generated by work-convention plugin install-git-hooks.sh
exec bash "$PLUGIN_ROOT/hooks/precommit-ticket-id-required.sh" "\$1"
HOOK
chmod +x "$HOOKS_DIR/commit-msg"
echo "✅ commit-msg → precommit-ticket-id-required.sh"

# pre-commit-Hook (für gitleaks)
cat > "$HOOKS_DIR/pre-commit" <<HOOK
#!/usr/bin/env bash
# auto-generated by work-convention plugin install-git-hooks.sh
export PLUGIN_ROOT="$PLUGIN_ROOT"
exec bash "$PLUGIN_ROOT/hooks/gitleaks-precommit.sh"
HOOK
chmod +x "$HOOKS_DIR/pre-commit"
echo "✅ pre-commit  → gitleaks-precommit.sh"

# pre-push-Hook (für branch-fresh + tests)
cat > "$HOOKS_DIR/pre-push" <<HOOK
#!/usr/bin/env bash
# auto-generated by work-convention plugin install-git-hooks.sh
set -uo pipefail
export PLUGIN_ROOT="$PLUGIN_ROOT"
bash "$PLUGIN_ROOT/hooks/pre-branch-fresh.sh" || exit \$?
bash "$PLUGIN_ROOT/hooks/pre-push-tests.sh" || exit \$?
HOOK
chmod +x "$HOOKS_DIR/pre-push"
echo "✅ pre-push    → pre-branch-fresh.sh + pre-push-tests.sh"

echo ""
echo "🎉 Git-Hooks installiert in: $HOOKS_DIR"
echo ""
echo "Note: seit v2.0 hält session-start-ensure-git-hooks.sh die Wrapper bei"
echo "      jedem Session-Start automatisch auf der aktuellen Plugin-Version —"
echo "      manuelles Nachziehen nach Updates entfällt."
